apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/zabbix-postgres-v2