apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-postgres-pvc
  namespace: monitoring
spec:
  storageClassName: local-storage
  volumeName: zabbix-postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
