apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgres-svc
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: zabbix-postgres
  ports:
    - port: 5432
      targetPort: 5432