apiVersion: apps/v1
kind: Deployment
metadata:
  name: techshop-micro-deployment-postgres-orders
  namespace: techshop-micro
  labels:
    app: postgres-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-orders
  template:
    metadata:
      labels:
        app: postgres-orders
    spec:
      containers:
      - name: postgres-orders
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: techshop-micro-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: techshop-micro-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          value: techshopdb