---
- name: Получить имя MongoDB пода
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: techshop-micro-service
    label_selectors:
      - app=mongo
  register: mongo_pod

- name: MongoDB collection products
  kubernetes.core.k8s_exec:
    namespace: techshop-micro-service
    pod: "{{ mongo_pod.resources[0].metadata.name }}"
    command: mongosh --eval "db.getSiblingDB('techshop').createCollection('products')"

- name: MongoDB collection categories
  kubernetes.core.k8s_exec:
    namespace: techshop-micro-service
    pod: "{{ mongo_pod.resources[0].metadata.name }}"
    command: mongosh --eval "db.getSiblingDB('techshop').createCollection('categories')"