apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: techshop-micro-service
  labels:
    app: zookeeper
spec:
  clusterIP: None
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: quorum
    - port: 3888
      name: leader-election
  selector:
    app: zookeeper