apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume
  namespace: techshop-micro-service
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data