apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: techshop-micro
spec:
  selector:
    app: techshop-micro-product
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP