apiVersion: v1
kind: Secret
metadata:
  name: techshop-micro-secret
  namespace: techshop-micro
type: Opaque
data:
  JWT_SECRET_KEY: bXlzZWNyZXQ
  POSTGRES_PASSWORD: cm9vdA
  JWT_SECRET: bXlzZWNyZXQ
  MONGO_INITDB_ROOT_PASSWORD: cm9vdA 
